In [ ]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
# यह कोड 'Review Rating' कॉलम में मौजूद गुम हुई (missing) वैल्यूज़ को भरने का काम करता है।
# यह पहले डेटाफ्रेम को 'Category' कॉलम के अनुसार समूहित करता है।
# फिर, प्रत्येक 'Category' के लिए, यह 'Review Rating' कॉलम की माध्यिका (median) की गणना करता है।
# अंत में, यह उसी श्रेणी की माध्यिका का उपयोग करके 'Review Rating' कॉलम में किसी भी गुम हुई वैल्यूज़ को भर देता है।

In [ ]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
#create the group
labels = ['Young Adult','Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels  )

In [ ]:
df[['age','age_group']].head(20)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
5    46  Middle-aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle-aged
10   53  Middle-aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior
15   64       Senior
16   25  Young Adult
17   53  Middle-aged
18   52  Middle-aged
19   66       Senior

In [ ]:
# Frequency of purchase mapping with corrected casing and spelling
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,

    'Every 3 Months': 90,

}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [ ]:
df[['purchase_frequency_days','frequency_of_purchases']].head(50)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly
20                       90         Every 3 Months
21                       90              Quarterly
22                      365               Annually
23                        7                 Weekly
24                        7                 Weekly
25                      365               Annually
26                      365               Annually
27                       90         Every 3 Months
28                       90         Every 3 Months
29                        7                 Weekly
30                       30                Monthly
31                       30                Monthly
32                      365               Annually
33                       90              Quarterly
34                       90              Quarterly
35                       14              Bi-Weekly
36                       14            Fortnightly
37                        7                 Weekly
38                       90         Every 3 Months
39                       30                Monthly
40                       90              Quarterly
41                      365               Annually
42                      365               Annually
43                       14            Fortnightly
44                        7                 Weekly
45                      365               Annually
46                       90              Quarterly
47                        7                 Weekly
48                       30                Monthly
49                       14              Bi-Weekly

In [ ]:
df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 55.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [ ]:
# connect the postgredsql
# from sqlalchemy import create_engine

# DATABASE_URL = "postgresql://neondb_owner:npg_GfgCBkS76qQe@ep-lively-boat-ad11h7fu-pooler.c-2.us-east-1.aws.neon.tech/neondb"

# engine = create_engine(DATABASE_URL)

# try:
#     with engine.connect() as conn:
#         print("Database connected successfully")
# except Exception as e:
#     print(e)

In [ ]:
from sqlalchemy import create_engine, text
import pandas as pd

# Aapki details
DB_USER = "postgres"
DB_PASS = "9111752952"
NGROK_HOST = "0.tcp.in.ngrok.io"
NGROK_PORT = "16677"
DB_NAME = "customer_behavior"

conn_string = f"postgresql://{DB_USER}:{DB_PASS}@{NGROK_HOST}:{NGROK_PORT}/{DB_NAME}"

try:
    engine = create_engine(conn_string)

    with engine.connect() as conn:
        # Query ko hamesha text() mein wrap karein
        query = text("SELECT current_database(), version();")
        res = conn.execute(query).fetchone()

        print("✅ Connection Successful!")
        print(f"Connected to Database: {res[0]}")
        print(f"PostgreSQL Version: {res[1]}")

except Exception as e:
    print("❌ Error details:")
    print(e)

# --- Pandas Test ---
# Agar aapke paas koi table hai toh uska naam yaha likhein:
# try:
#     df = pd.read_sql(text("SELECT * FROM your_table_name LIMIT 5"), engine)
#     print(df)
# except:
#     print("Table nahi mili ya query galat hai.")

❌ Error details:
(psycopg2.OperationalError) connection to server at "0.tcp.in.ngrok.io" (13.232.253.105), port 16677 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "0.tcp.in.ngrok.io" (13.202.67.218), port 16677 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "0.tcp.in.ngrok.io" (13.233.222.52), port 16677 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "0.tcp.in.ngrok.io" (13.200.54.243), port 16677 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "0.tcp.in.ngrok.io" (3.6.231.193), port 16677 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

# Database connection details (from previous cells)
DB_USER = "postgres"
DB_PASS = "9111752952"
NGROK_HOST = "0.tcp.in.ngrok.io"
NGROK_PORT = "11705"
DB_NAME = "customer_behavior"

conn_string = f"postgresql://{DB_USER}:{DB_PASS}@{NGROK_HOST}:{NGROK_PORT}/{DB_NAME}"

try:
    engine = create_engine(conn_string)
    # Load DataFrame to PostgreSQL
    # Using 'replace' for simplicity, change to 'append' or 'fail' as needed
    df.to_sql('customer_shopping_behavior', engine, if_exists='replace', index=False)
    print("✅ DataFrame loaded successfully to the 'customer_shopping_behavior' table.")
except Exception as e:
    print(f"❌ Error loading DataFrame to database: {e}")
    print("Please ensure the database server is running and accessible.")

✅ DataFrame loaded successfully to the 'customer_shopping_behavior' table.